export const chapter10Questions = [
  {
    number: 1,
    topic: "第十章 TCP/UDP協定",
    description:
      "當 TCP/IP 網路連線時,可以透過 ___ 進行檢視目前主機上連線狀態與封包的統計資訊等等。",
    answer: 4,
    options: [
      { label: 1, description: "ping" },
      { label: 2, description: "cd" },
      { label: 3, description: "arp" },
      { label: 4, description: "netstat" },
    ],
  },
  {
    number: 2,
    topic: "第十章 TCP/UDP協定",
    description: "TCP 標頭的長度為 ___ bytes。",
    answer: 1,
    options: [
      { label: 1, description: "20" },
      { label: 2, description: "32" },
      { label: 3, description: "8" },
      { label: 4, description: "24" },
    ],
  },
  {
    number: 3,
    topic: "第十章 TCP/UDP協定",
    description: "UCP 標頭的長度為 ___ bytes。",
    answer: 3,
    options: [
      { label: 1, description: "20" },
      { label: 2, description: "32" },
      { label: 3, description: "8" },
      { label: 4, description: "24" },
    ],
  },
  {
    number: 4,
    topic: "第十章 TCP/UDP協定",
    description: "TCP 連線建立的過程 3 個順序步驟為 ___。",
    answer: 1,
    options: [
      { label: 1, description: "SYN, SYN-ACK, ACK" },
      { label: 2, description: "SYN-ACK, SYN, ACK" },
      { label: 3, description: "SYN, ACK, SYN-ACK" },
      { label: 4, description: "ACK, SYN-ACK, SYN" },
    ],
  },
  {
    number: 5,
    topic: "第十章 TCP/UDP協定",
    description: "TCP 進行雙方的同步溝通時,那一位元會被設定為 1。",
    answer: 4,
    options: [
      { label: 1, description: "FIN" },
      { label: 2, description: "FO" },
      { label: 3, description: "ACK" },
      { label: 4, description: "SYN" },
    ],
  },
  {
    number: 6,
    topic: "第十章 TCP/UDP協定",
    description: "哪一種協定需要三方交握。",
    answer: 4,
    options: [
      { label: 1, description: "ARP" },
      { label: 2, description: "ICMP" },
      { label: 3, description: "UDP" },
      { label: 4, description: "TCP" },
    ],
  },
  {
    number: 7,
    topic: "第十章 TCP/UDP協定",
    description: "TCP 協定的 16 進位值為 ___。",
    answer: 2,
    options: [
      { label: 1, description: "0x01" },
      { label: 2, description: "0x06" },
      { label: 3, description: "0x11" },
      { label: 4, description: "0x17" },
    ],
  },
  {
    number: 8,
    topic: "第十章 TCP/UDP協定",
    description: "UDP 協定的 16 進位值為 ___。",
    answer: 3,
    options: [
      { label: 1, description: "0x01" },
      { label: 2, description: "0x06" },
      { label: 3, description: "0x11" },
      { label: 4, description: "0x17" },
    ],
  },
  {
    number: 9,
    topic: "第十章 TCP/UDP協定",
    description:
      "某一方告訴對方自己 TCP 傳送資料已經結束,那一位元會被設定為 1。",
    answer: 1,
    options: [
      { label: 1, description: "FIN" },
      { label: 2, description: "FCS" },
      { label: 3, description: "ACK" },
      { label: 4, description: "SYN" },
    ],
  },
  {
    number: 10,
    topic: "第十章 TCP/UDP協定",
    description:
      "主機 A 在確定主機 B 正確地收到目前所傳送的封包之前,不會再傳送新的資料稱為 ______ 協定。",
    answer: 3,
    options: [
      { label: 1, description: "GBN" },
      { label: 2, description: "SR" },
      { label: 3, description: "停止並等待 (Stop-and-Wait)" },
      { label: 4, description: "以上皆可" },
    ],
  },
  {
    number: 11,
    topic: "第十章 TCP/UDP協定",
    description:
      "TCP 允許傳送端只重送它接收端未正確收到(指遺失或損毀)的封包稱為 _______。",
    answer: 3,
    options: [
      { label: 1, description: "TCP Socket" },
      { label: 2, description: "GBN" },
      { label: 3, description: "SR" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 12,
    topic: "第十章 TCP/UDP協定",
    description:
      "_____ 傳輸的應用可以用任何它想要的速率來傳送資料,且想傳送多久就傳多久。",
    answer: 3,
    options: [
      { label: 1, description: "TCP" },
      { label: 2, description: "IP" },
      { label: 3, description: "UDP" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 13,
    topic: "第十章 TCP/UDP協定",
    description: "UDP Socket 是由 ____ 位址與目的端埠號來加以識別。",
    answer: 1,
    options: [
      { label: 1, description: "目的端 IP" },
      { label: 2, description: "來源端 IP" },
      { label: 3, description: "目的端 IP 與來源端 IP" },
      { label: 4, description: "以上皆可" },
    ],
  },
  {
    number: 14,
    topic: "第十章 TCP/UDP協定",
    description: "TCP Socket 是由 ____ 項數值來加以識別。",
    answer: 3,
    options: [
      { label: 1, description: "2" },
      { label: 2, description: "3" },
      { label: 3, description: "4" },
      { label: 4, description: "5" },
    ],
  },
  {
    number: 15,
    topic: "第十章 TCP/UDP協定",
    description:
      "TCP 允許傳送端可以無需等待確認就可以傳輸多份封包稱為 _______。",
    answer: 2,
    options: [
      { label: 1, description: "TCP Socket" },
      { label: 2, description: "滑動窗格協定(又稱 Go-Back-N)" },
      { label: 3, description: "Stop-and-Wait" },
      { label: 4, description: "以上皆非" },
    ],
  },
];

export const chapter11Questions = [
  {
    number: 1,
    topic: "第十一章 DNS協定",
    description: "網域「.yahoo.com.tw.」、「.google.com.tw.」均同屬於 ___。",
    answer: 3,
    options: [
      { label: 1, description: "根網域" },
      { label: 2, description: "頂層網域" },
      { label: 3, description: "第二層網域" },
      { label: 4, description: "主機名稱" },
    ],
  },
  {
    number: 2,
    topic: "第十一章 DNS協定",
    description:
      "在 Internet 上的著名機構大都擁有供給眾多人存取的主機稱為 ___。",
    answer: 3,
    options: [
      { label: 1, description: "根 DNS 伺服器" },
      { label: 2, description: "頂層網域 DNS 伺服器" },
      { label: 3, description: "官方 DNS 伺服器" },
      { label: 4, description: "NAT 以提供給客戶存取的 DNS 記錄" },
    ],
  },
  {
    number: 3,
    topic: "第十一章 DNS協定",
    description: "當客戶端主機送出 DNS 查詢訊息時,就會先送至 ___。",
    answer: 4,
    options: [
      { label: 1, description: "根 DNS 伺服器" },
      { label: 2, description: "頂層網域 DNS 伺服器" },
      { label: 3, description: "官方 DNS 伺服器" },
      { label: 4, description: "本地 DNS 伺服器" },
    ],
  },
  {
    number: 4,
    topic: "第十一章 DNS協定",
    description: "哪一種 DNS 伺服器沒有管理任何的 Zone?",
    answer: 3,
    options: [
      { label: 1, description: "主要名稱 DNS 伺服器" },
      { label: 2, description: "次要名稱 DNS 伺服器" },
      { label: 3, description: "快取 DNS 伺服器" },
      { label: 4, description: "以上皆可" },
    ],
  },
  {
    number: 5,
    topic: "第十一章 DNS協定",
    description: "DNS 的封包格式其中標頭的長度是固定的,共佔幾個 bytes?",
    answer: 4,
    options: [
      { label: 1, description: "4" },
      { label: 2, description: "8" },
      { label: 3, description: "10" },
      { label: 4, description: "12" },
    ],
  },
  {
    number: 6,
    topic: "第十一章 DNS協定",
    description: "當名稱伺服器錯誤時,其 rCode 的欄位值為 ___。",
    answer: 2,
    options: [
      { label: 1, description: "1" },
      { label: 2, description: "2" },
      { label: 3, description: "3" },
      { label: 4, description: "4" },
    ],
  },
  {
    number: 7,
    topic: "第十一章 DNS協定",
    description: "Zone 檔案內的一開始就是何種記錄?",
    answer: 4,
    options: [
      { label: 1, description: "PTR" },
      { label: 2, description: "NS" },
      { label: 3, description: "A" },
      { label: 4, description: "SOA" },
    ],
  },
  {
    number: 8,
    topic: "第十一章 DNS協定",
    description: "哪一種 RR 可以對同一部主機設定不同的別名 (alias)?",
    answer: 3,
    options: [
      { label: 1, description: "AAAA" },
      { label: 2, description: "MX" },
      { label: 3, description: "CNAME" },
      { label: 4, description: "NS" },
    ],
  },
  {
    number: 9,
    topic: "第十一章 DNS協定",
    description: "DNS 是一種讓主機可以查詢此一分散式資料庫的 ____ 協定。",
    answer: 4,
    options: [
      { label: 1, description: "數據鏈路層" },
      { label: 2, description: "網路層" },
      { label: 3, description: "傳輸層" },
      { label: 4, description: "應用層" },
    ],
  },
  {
    number: 10,
    topic: "第十一章 DNS協定",
    description: "DNS 協定是透過 UDP 來運作,使用埠號 ____。",
    answer: 4,
    options: [
      { label: 1, description: "25" },
      { label: 2, description: "32" },
      { label: 3, description: "48" },
      { label: 4, description: "53" },
    ],
  },
];

export const chapter14Questions = [
  {
    number: 1,
    topic: "第十四章 HTTP協定",
    description: "Web Browser 是透過何者向 WWW 伺服器擷取資訊?",
    answer: 3,
    options: [
      { label: 1, description: "IP" },
      { label: 2, description: "TCP" },
      { label: 3, description: "HTTP" },
      { label: 4, description: "PPP" },
    ],
  },
  {
    number: 2,
    topic: "第十四章 HTTP協定",
    description: "HTTP 協定屬於哪一層?",
    answer: 3,
    options: [
      { label: 1, description: "表現層" },
      { label: 2, description: "交談層" },
      { label: 3, description: "應用層" },
      { label: 4, description: "傳輸層" },
    ],
  },
  {
    number: 3,
    topic: "第十四章 HTTP協定",
    description: "一個物件指的就是幾個檔案?",
    answer: 1,
    options: [
      { label: 1, description: "1" },
      { label: 2, description: "2" },
      { label: 3, description: "3" },
      { label: 4, description: "4" },
    ],
  },
  {
    number: 4,
    topic: "第十四章 HTTP協定",
    description: "GET 指令屬於哪一個方法?",
    answer: 2,
    options: [
      { label: 1, description: "標頭列" },
      { label: 2, description: "要求列" },
      { label: 3, description: "狀態列" },
      { label: 4, description: "回覆列" },
    ],
  },
  {
    number: 5,
    topic: "第十四章 HTTP協定",
    description: "200 OK 代表什麼類型的代碼?",
    answer: 1,
    options: [
      { label: 1, description: "狀態碼" },
      { label: 2, description: "要求碼" },
      { label: 3, description: "標頭碼" },
      { label: 4, description: "回覆碼" },
    ],
  },
  {
    number: 6,
    topic: "第十四章 HTTP協定",
    description: "HTTP 協定的屬性是什麼?",
    answer: 1,
    options: [
      { label: 1, description: "無態(stateless)協定" },
      { label: 2, description: "狀態(state)協定" },
      { label: 3, description: "無態+狀態協定" },
      { label: 4, description: "以上皆可" },
    ],
  },
  {
    number: 7,
    topic: "第十四章 HTTP協定",
    description: "FTP 協定的屬性是什麼?",
    answer: 2,
    options: [
      { label: 1, description: "無態(stateless)協定" },
      { label: 2, description: "狀態(state)協定" },
      { label: 3, description: "無態+狀態協定" },
      { label: 4, description: "以上皆可" },
    ],
  },
  {
    number: 8,
    topic: "第十四章 HTTP協定",
    description: "HTTPS 是 HTTP 和什麼的組合?",
    answer: 4,
    options: [
      { label: 1, description: "SSH" },
      { label: 2, description: "TCP" },
      { label: 3, description: "UDP" },
      { label: 4, description: "SSL/TLS" },
    ],
  },
  {
    number: 9,
    topic: "第十四章 HTTP協定",
    description: "SSL/TLS 預定的 port 號碼為?",
    answer: 3,
    options: [
      { label: 1, description: "301" },
      { label: 2, description: "304" },
      { label: 3, description: "443" },
      { label: 4, description: "501" },
    ],
  },
  {
    number: 10,
    topic: "第十四章 HTTP協定",
    description: "為了讓網站辨識使用者身份,需要使用什麼功能?",
    answer: 3,
    options: [
      { label: 1, description: "GET" },
      { label: 2, description: "POST" },
      { label: 3, description: "Cookie" },
      { label: 4, description: "HEAD" },
    ],
  },
  {
    number: 11,
    topic: "第十四章 HTTP協定",
    description: "HTTP/2 與 HTTP/1.1 比較,前者具有什麼優點?",
    answer: 4,
    options: [
      { label: 1, description: "對 HOL blocking 問題有所修正" },
      { label: 2, description: "單一條的 TCP 連線來一次傳送多個資料流" },
      { label: 3, description: "更高的速度" },
      { label: 4, description: "以上皆是" },
    ],
  },
  {
    number: 12,
    topic: "第十四章 HTTP協定",
    description: "一封包從客戶端至伺服器再回到客戶端,所花掉的時間為?",
    answer: 2,
    options: [
      { label: 1, description: "1 RTT" },
      { label: 2, description: "2 RTT" },
      { label: 3, description: "3 RTT" },
      { label: 4, description: "4 RTT" },
    ],
  },
  {
    number: 13,
    topic: "第十四章 HTTP協定",
    description: "HTTPS 可看成 HTTP 工作在什麼樣的連線上的協定?",
    answer: 3,
    options: [
      { label: 1, description: "點對點" },
      { label: 2, description: "不加密" },
      { label: 3, description: "加密" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 14,
    topic: "第十四章 HTTP協定",
    description: "想了解 HTTP over TLS,可參考 RFC?",
    answer: 4,
    options: [
      { label: 1, description: "2573" },
      { label: 2, description: "2475" },
      { label: 3, description: "2616" },
      { label: 4, description: "2818" },
    ],
  },
  {
    number: 15,
    topic: "第十四章 HTTP協定",
    description: "SSL 是位於什麼層之間的協定?",
    answer: 2,
    options: [
      { label: 1, description: "網路層之上,傳輸層之下" },
      { label: 2, description: "傳輸層之上,應用層之下" },
      { label: 3, description: "數據鏈路層之上,網路層之下" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 16,
    topic: "第十四章 HTTP協定",
    description: "下列哪一個稱為超文件傳輸協定?",
    answer: 4,
    options: [
      { label: 1, description: "PPP" },
      { label: 2, description: "FTP" },
      { label: 3, description: "TCP" },
      { label: 4, description: "HTTP" },
    ],
  },
  {
    number: 17,
    topic: "第十四章 HTTP協定",
    description: "HTTP 協定可由哪個埠號識別出來?",
    answer: 3,
    options: [
      { label: 1, description: "25" },
      { label: 2, description: "53" },
      { label: 3, description: "80" },
      { label: 4, description: "110" },
    ],
  },
  {
    number: 18,
    topic: "第十四章 HTTP協定",
    description: "HTTP/1.1 其下層使用哪種協定?",
    answer: 3,
    options: [
      { label: 1, description: "LCP" },
      { label: 2, description: "PPP" },
      { label: 3, description: "TCP" },
      { label: 4, description: "UDP" },
    ],
  },
  {
    number: 19,
    topic: "第十四章 HTTP協定",
    description: "HTTP 客戶端與 HTTP 伺服器之間實際的溝通時,使用什麼工具?",
    answer: 4,
    options: [
      { label: 1, description: "GET" },
      { label: 2, description: "POST" },
      { label: 3, description: "HEAD" },
      { label: 4, description: "Telnet 程式" },
    ],
  },
];

export const chapter15Questions = [
  {
    number: 1,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "小英想送郵件給大明,可使用 ___ 協定傳送出去。",
    answer: 4,
    options: [
      { label: 1, description: "BOOTP" },
      { label: 2, description: "NAT" },
      { label: 3, description: "DCHP" },
      { label: 4, description: "SMTP" },
    ],
  },
  {
    number: 2,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "大明想從郵件伺服器內部之郵箱取出該郵件可使用 ___ 協定。",
    answer: 3,
    options: [
      { label: 1, description: "SMTP" },
      { label: 2, description: "NAT" },
      { label: 3, description: "POP3" },
      { label: 4, description: "DHCP" },
    ],
  },
  {
    number: 3,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "SMTP 為應用層協定並使用 ___ 的傳輸服務。",
    answer: 2,
    options: [
      { label: 1, description: "IP" },
      { label: 2, description: "TCP" },
      { label: 3, description: "UDP" },
      { label: 4, description: "DHCP" },
    ],
  },
  {
    number: 4,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "SMTP 採用 ___ 方式和 ___ 連接。",
    answer: 1,
    options: [
      { label: 1, description: "內頻方式和持續性連接" },
      { label: 2, description: "外頻方式和持續性連接" },
      { label: 3, description: "外頻方式和非持續性連接" },
      { label: 4, description: "內頻方式和非持續性連接" },
    ],
  },
  {
    number: 5,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "IMAP 或 POP3 執行 ___ 動作。",
    answer: 4,
    options: [
      { label: 1, description: "push" },
      { label: 2, description: "upload" },
      { label: 3, description: "download" },
      { label: 4, description: "pull" },
    ],
  },
  {
    number: 6,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "SMTP 執行 ___ 動作。",
    answer: 1,
    options: [
      { label: 1, description: "push" },
      { label: 2, description: "upload" },
      { label: 3, description: "download" },
      { label: 4, description: "pull" },
    ],
  },
  {
    number: 7,
    topic: "第十五章 SMTP協定與POP3協定",
    description:
      "一旦小英寫好郵件,透過郵件讀取器將郵件轉交給___用戶端,透過網際網路,MTA 伺服端把郵件送出。",
    answer: 2,
    options: [
      { label: 1, description: "UA" },
      { label: 2, description: "MTA" },
      { label: 3, description: "DCHP" },
      { label: 4, description: "SMTP" },
    ],
  },
  {
    number: 8,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "UA 代表什麼?",
    answer: 1,
    options: [
      { label: 1, description: "執行使用者代理器" },
      { label: 2, description: "郵件伺服器" },
      { label: 3, description: "郵箱" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 9,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "用戶端和伺服端需要一對的郵件存取代理程式,稱為 ___。",
    answer: 3,
    options: [
      { label: 1, description: "UA" },
      { label: 2, description: "MTA" },
      { label: 3, description: "MAA" },
      { label: 4, description: "以上皆非" },
    ],
  },
  {
    number: 10,
    topic: "第十五章 SMTP協定與POP3協定",
    description: "當您想透過網頁瀏覽器來送收電子郵件(如 Hotmail),則用戶代理器至郵件伺服器之間是採用何種協定?",
    answer: 2,
    options: [
      { label: 1, description: "BOOTP" },
      { label: 2, description: "HTTP" },
      { label: 3, description: "TCP" },
      { label: 4, description: "SMTP" },
    ],
  },
];
